baseURL = ""
languageCode = "en-us"
title = "Example"
theme = "rocinante"
paginate = 3

[blackfriday] 
plainIDAnchors = false

[markup]
  [markup.highlight]
    style = "monokailight"
  [markup.goldmark.renderer]
    unsafe= true

[params]
  favicon = "/icons/favicon.png"
  mainSections = ["posts", "photos"]
  email = "not-real@gmail.com"
  about = """
"""


  [[params.links]]
    [[params.links.link]]
      name = "Email"
      href = "/contact"
      smart_email_link = true
    [[params.links.link]]
      name = "Github"
      href = "https://github.com/kc-tal"
      new_tab = true

